-- POCOS Supabase Migration Script
-- Run this AFTER the initial SUPABASE_SETUP.sql to add new features
-- This adds support for Profiles, Bird Cages, Bird Count Records, and Notes

-- 1. PROFILES TABLE
-- Profiles allow managing different animal types (cattle, sheep, goat, horse, donkey, bird)
-- with custom fields specific to each profile type
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ranch_id UUID REFERENCES ranch(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  animal_type TEXT NOT NULL CHECK (animal_type IN ('cattle', 'sheep', 'goat', 'horse', 'donkey', 'bird')),
  description TEXT,
  custom_fields JSONB DEFAULT '[]'::jsonb, -- Array of {id, label, fieldType, value}
  device_address TEXT CHECK (device_address ~ '^[a-f0-9]{16}$'), -- 16-character hex address for IoT devices (e.g., 989347d6c29e5e8b)
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. BIRD CAGES TABLE
-- Cages for bird profiles to track individual cage counts
CREATE TABLE IF NOT EXISTS bird_cages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  cage_id TEXT NOT NULL, -- Human readable cage identifier
  capacity INTEGER,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(profile_id, cage_id)
);

-- 3. BIRD COUNT RECORDS TABLE
-- Tracks bird counts over time for monitoring and history
CREATE TABLE IF NOT EXISTS bird_count_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  cage_id UUID REFERENCES bird_cages(id) ON DELETE SET NULL,
  count INTEGER NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. POULTRY REAL-TIME MONITORING
-- History table for 15-min logs
CREATE TABLE IF NOT EXISTS bird_counts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  total_birds INTEGER NOT NULL,
  interval_birds INTEGER NOT NULL,
  device_id TEXT NOT NULL
);

-- Live status table for real-time feed
CREATE TABLE IF NOT EXISTS poultry_live_status (
  id TEXT PRIMARY KEY, -- use 'current_status' as ID
  last_updated TIMESTAMPTZ DEFAULT NOW(),
  total_count INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true
);

-- Enable Realtime for these tables
-- Note: This requires superuser permissions in Supabase
-- CREATE PUBLICATION supabase_realtime FOR TABLE bird_counts, poultry_live_status;

-- Initialize the live status row
INSERT INTO poultry_live_status (id, total_count, last_updated, is_active)
VALUES ('current_status', 0, NOW(), true)
ON CONFLICT (id) DO NOTHING;

-- Disable RLS for these tables to allow external updates (e.g., from IoT devices)
ALTER TABLE poultry_live_status DISABLE ROW LEVEL SECURITY;
ALTER TABLE bird_counts DISABLE ROW LEVEL SECURITY;

-- 5. NOTES TABLE
-- General notes for animals, tasks, or other entities
-- Check if table exists and add columns if needed
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_tables WHERE tablename = 'notes') THEN
    CREATE TABLE notes (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      ranch_id UUID REFERENCES ranch(id) ON DELETE CASCADE,
      user_id UUID REFERENCES ranch_users(id) ON DELETE SET NULL,
      entity_type TEXT NOT NULL, -- e.g., "animal", "task", "profile"
      entity_id UUID,
      title TEXT,
      content TEXT NOT NULL,
      is_pinned BOOLEAN DEFAULT false,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );
  ELSE
    -- Add missing columns if they don't exist
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'notes' AND column_name = 'entity_type') THEN
      ALTER TABLE notes ADD COLUMN entity_type TEXT NOT NULL DEFAULT 'animal';
    END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'notes' AND column_name = 'entity_id') THEN
      ALTER TABLE notes ADD COLUMN entity_id UUID;
    END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'notes' AND column_name = 'is_pinned') THEN
      ALTER TABLE notes ADD COLUMN is_pinned BOOLEAN DEFAULT false;
    END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'notes' AND column_name = 'updated_at') THEN
      ALTER TABLE notes ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
    END IF;
  END IF;
END $$;

-- 5. UPDATE ANIMALS TABLE
-- Add animal_type column to support multi-animal profiles
ALTER TABLE animals ADD COLUMN IF NOT EXISTS animal_type TEXT DEFAULT 'cattle' CHECK (animal_type IN ('cattle', 'sheep', 'goat', 'horse', 'donkey', 'bird'));

-- Add profile_id column to link animals to profiles
ALTER TABLE animals ADD COLUMN IF NOT EXISTS profile_id UUID REFERENCES profiles(id) ON DELETE SET NULL;

-- Add photos column (array) to replace single image_url
ALTER TABLE animals ADD COLUMN IF NOT EXISTS photos JSONB DEFAULT '[]'::jsonb;

-- 5.5 UPDATE PROFILES TABLE FOR DEVICE ADDRESS
-- Add device_address column if it doesn't exist, or update constraint if it does
DO $$
BEGIN
  -- Check if column exists
  IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'device_address') THEN
    ALTER TABLE profiles ADD COLUMN device_address TEXT CHECK (device_address ~ '^[a-f0-9]{16}$');
  ELSE
    -- Column exists, drop and recreate constraint to ensure hex format
    ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_device_address_check;
    ALTER TABLE profiles ADD CONSTRAINT profiles_device_address_check CHECK (device_address ~ '^[a-f0-9]{16}$' OR device_address IS NULL);
  END IF;
END $$;

-- 6. UPDATE CHAT MESSAGES TABLE
-- Add missing columns for message type and read status
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'text' CHECK (type IN ('text', 'image', 'file', 'system'));
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT false;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS read_by UUID[] DEFAULT '{}';
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 7. UPDATE TASKS TABLE
-- Add missing columns for attachments and tags
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS attachments JSONB DEFAULT '[]'::jsonb;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '[]'::jsonb;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS recurrence TEXT DEFAULT 'none' CHECK (recurrence IN ('none', 'daily', 'weekly', 'monthly', 'custom'));

-- 8. UPDATE TASK COMMENTS TABLE
-- Add time column for display
ALTER TABLE task_comments ADD COLUMN IF NOT EXISTS time TIMESTAMPTZ DEFAULT NOW();

-- 9. INDEXES FOR PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_profiles_ranch_id ON profiles(ranch_id);
CREATE INDEX IF NOT EXISTS idx_profiles_animal_type ON profiles(animal_type);
CREATE INDEX IF NOT EXISTS idx_bird_cages_profile_id ON bird_cages(profile_id);
CREATE INDEX IF NOT EXISTS idx_bird_count_records_profile_id ON bird_count_records(profile_id);
CREATE INDEX IF NOT EXISTS idx_bird_count_records_timestamp ON bird_count_records(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_notes_ranch_id ON notes(ranch_id);
CREATE INDEX IF NOT EXISTS idx_notes_entity ON notes(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_animals_profile_id ON animals(profile_id);
CREATE INDEX IF NOT EXISTS idx_animals_animal_type ON animals(animal_type);

-- 10. ENABLE ROW LEVEL SECURITY
-- Skip if already configured (policies exist)
DO $$
BEGIN
  -- Only enable RLS if not already enabled
  IF NOT EXISTS (SELECT FROM pg_policies WHERE schemaname = 'public' AND tablename = 'profiles') THEN
    ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Ranch members can manage profiles" ON profiles FOR ALL USING (true);
  END IF;

  IF NOT EXISTS (SELECT FROM pg_policies WHERE schemaname = 'public' AND tablename = 'bird_cages') THEN
    ALTER TABLE bird_cages ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Ranch members can manage bird cages" ON bird_cages FOR ALL USING (true);
  END IF;

  IF NOT EXISTS (SELECT FROM pg_policies WHERE schemaname = 'public' AND tablename = 'bird_count_records') THEN
    ALTER TABLE bird_count_records ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Ranch members can manage bird count records" ON bird_count_records FOR ALL USING (true);
  END IF;

  IF NOT EXISTS (SELECT FROM pg_policies WHERE schemaname = 'public' AND tablename = 'notes') THEN
    ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Ranch members can manage notes" ON notes FOR ALL USING (true);
  END IF;
END $$;

-- 11. ENABLE REALTIME FOR NEW TABLES
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'bird_count_records'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE bird_count_records;
  END IF;

  IF NOT EXISTS (
    SELECT FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'notes'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE notes;
  END IF;
END $$;
